general_configs:
  db_location: "local"

printer_configs:
  network_address: "10.69.69.10"

logging:
  loglevel:
  logfile:

database:
  local:
    db_config:
      ENGINE: 'django.db.backends.sqlite3'
      NAME: 'db.dnd'
  remote1:
    db_config:
      ENGINE: 'django.db.backends.mysql'
      NAME: "dnd"
      USER: "admin"
      PASSWORD: "PASSWORD"
      HOST: "dnd.cluster-somethingsomething.rds.amazonaws.com"
      PORT: "3306"


